version: "3.4"
services: 
    db:
        image: microsoft/mssql-server-linux:latest
        environment: 
            - ACCEPT_EULA=Y
            - SA_PASSWORD=DevelopmentTmpPassword22
        networks: 
            - backend
    nginx:
        restart: always
        build:
            dockerfile: Dockerfile
            context: ./nginx
        ports: 
            - '8080:80'
        networks: 
            - frontend
            - backend
    api:
        build:
            dockerfile: Dockerfile
            context: ./api/covid-monitor-api
        ports: 
            - '8090'
        volumes:
            - ./api:/app
        networks:
            - frontend
            - backend
    client:
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        environment:
            - NODE_ENV=development
            - CHOKIDAR_USEPOLLING=true
        volumes:
            - /app/node_modules
            - ./client:/app
        networks:
            - frontend
networks:
    frontend:
    backend:

    