// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using covid_monitor_api.Models;
using covid_monitor_api.Authentication;

namespace covid_monitor_api.Migrations.DailyInformationForm
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20210614094143_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("covid_monitor_api.Models.DailyInformationForm", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("BloodPressure")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ChestPain")
                        .HasColumnType("int");

                    b.Property<int>("DiffBreathing")
                        .HasColumnType("int");

                    b.Property<bool>("DryCough")
                        .HasColumnType("bit");

                    b.Property<int>("Fatigue")
                        .HasColumnType("int");

                    b.Property<int>("Headache")
                        .HasColumnType("int");

                    b.Property<bool>("LossOfTaste")
                        .HasColumnType("bit");

                    b.Property<int>("MusclePain")
                        .HasColumnType("int");

                    b.Property<string>("OwnerId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Pulse")
                        .HasColumnType("int");

                    b.Property<bool>("RunningNose")
                        .HasColumnType("bit");

                    b.Property<int>("Saturation")
                        .HasColumnType("int");

                    b.Property<int>("Temperature")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("DailyInformations");
                });
#pragma warning restore 612, 618
        }
    }
}
